### ISSUE TITLE
テンポが悪い

### ISSUE THREAD

**Issue by ichigotake** [ichigotake/murisara150#12]
説明的で冗長なところが多かったり文字数が多かったり。

とはいっても、簡潔な表現がノータイムで思い浮かぶわけでもない。

**Comment by note103** [comment]
#15 や #13 にもつながりますが、本件も執筆中にはあまり気にしなくてよいかなと思います。

最初の目的はとりあえず「書きたいことを書き漏らしなく全部書く」ということにして、それが終わってから「推敲作業」として、一旦書き終えた内容から要不要を判断して取捨選択したり、重複をカットしたり、わかりづらい説明を書き直したり、ということをやる感じになると思いますので。

「テンポは良いけど内容が間違ってる本」と、「テンポは悪いけど内容が良い本」があったら、後者のほうが読者にとってはありがたいですし、著者としてもそれを目指したいところかなと。

であれば、まずは良い内容を作って、その後に、内容を壊さずに文章をわかりやすくする、というふうにした方がいいかなと。

よって、これも「保留」系のIssueかなと思いました。
