### ISSUE TITLE
箇条書きにおける文字数の目安を決めておく

### ISSUE THREAD

**Issue by ichigotake** [ichigotake/murisara150#13]

**Comment by note103** [comment]
本件の調整というか検討に関しては、終盤のほうで良いかな、と感じます。

「読みやすい文章量にすること」と「必要な内容が記載されていること」を比べたら後者の方が大事なので、1行あたりの文字量に縛られて本来必要な情報が不十分になる可能性があることを考えたら、まずはその辺は気にせず、必要な内容を全部書く、というのを先に行うほうがいいかなと。

また、仮に「1行につき80文字まで」と最初に決めたとしても、後から全体を見直して「やっぱり70文字が適切だ」と思った場合にそれまでの基準がほぼ無駄になってしまうので、その意味でもあまり前半作業のうちには考えなくてもいいのかなと。

ただし、ゆくゆく検討要素に入れるのは良いこととも思いますので、チェック項目として残しておきたい場合には、このIssueに「保留」とか「あとで読む」的なラベルを付けておいて、必要になったときに見直す、とかはしてもいいかもしれませんが。
