### ISSUE TITLE
文体を決める

### ISSUE THREAD

**Issue by ichigotake** [ichigotake/murisara150#15]
[フォーマット](https://github.com/ichigotake/murisara150/blob/master/CONTRIBUTING.md#現時点で決まっていないこと) における各項目の文字数はイメージ出来るようになってきたが、文体はこれで良いのか再考する。

文章のテンポが悪い（ #12 ）から文体が気になってしまうだけかもしれない。

迷ったら今のまま進めていくつもりです。

**Comment by note103** [comment]
Help! ラベルのOpened Issuesこの週末に少し見られると思います。とりあえず予告まで

**Comment by note103** [comment]
「文体」というのは、具体的には「です・ます（敬体）」にするか、「だ・である（常体）」にするか、という意味でしょうかね？

もしそうでしたら、リファレンス（教科書）的な性質を持つという意味でも、最終的には「です・ます（敬体）」の方が良い気はします。

逆に、ある程度レベルの高い読者に向けて書く専門的な本とかであれば、「だ・である（常体）」の方がしっくりくる場合もあると思います。

ようは「誰に向けて書くのか」という対象読者による、という感じでしょうか。
初心者（そのゲームをまったく知らない人）も想定読者に入るようであれば、優しいトーンで丁寧に書く方がいいのかなと。

ただ、それはそれとして、執筆初期というのは想定読者があまり固まっていない方が普通なので、そういうときは「だ・である」で書き始めちゃった方が執筆自体は進む、ということもあると思います。

というか、僕自身がそうなのですが、最初は「自分の書きたいことを書く」のが目的なので、常体で一気に書き始めて、でも書いてるうちにだんだん読者の顔が見えてくると、今度は敬体（です・ます）の方が書きやすくなります。

言い換えると、敬体（です・ます）はけっこうまどろっこしいので、書きたことがあふれている時に敬体で書こうとすると、手が頭に追いつかなくて、効率が悪いんですよね。でも、それがだんだん読者の存在を想像できるようになってくると、今度は常体だとやけにぶっきらぼうな調子に感じられてきて、常体のほうが書きづらくなる、という感覚がありますね。
あくまで個人的な感覚ですが。

その上で、結局全体の雰囲気の統一というのは最後にやらないと効率が悪いという面もあるので、結論的には、執筆中にはその辺はあまり気にしないで、敬体と常体が混在してもいいので一旦書きたい内容を全部書いて、その後の推敲作業のときに統一させればいいとも感じます。

まとめると、

1. 最終的には敬体（です・ます）の方がいい気はする。
2. ただし執筆中は、常体（だ・である）の方が書きやすければそれでいいし、混在してもいいので一旦最後まで書くことを優先する。
3. 2が終わってから全体を統一する。

という感じでしょうか。

**Comment by ichigotake** [comment]
>ただ、それはそれとして、執筆初期というのは想定読者があまり固まっていない方が普通なので、そういうときは「だ・である」で書き始めちゃった方が執筆自体は進む、ということもあると思います。


>最終的には敬体（です・ます）の方がいい気はする。
>ただし執筆中は、常体（だ・である）の方が書きやすければそれでいいし、混在してもいいので一旦最後まで書くことを優先する。
>2が終わってから全体を統一する。
>という感じでしょうか。

言われてみるとそうですね。

少なくとも今月いっぱいは一人で書いていこうと思います。

また困った事があった際にお声をかけます。
