### ISSUE TITLE
英数字の前後に半角スペースを入れるべきか

### ISSUE THREAD

**Issue by ichigotake** [ichigotake/murisara150#17]

**Comment by note103** [comment]
本件、優先的にコメントしてみます。

個人的にこの問題については結構考えたことがあるのですが、結論的には、他のコミットメッセージにもありましたように、最終的にはWeb+DBプレスが採用しているルールにそのまま合わせるのでよいと思います。

ただし経験的には、執筆中にいちいちそれについて気を回すのはけっこうな労力がかかるので、個人的には、「まずは英数字前後の半角スペースについては一切考えない＝英数字前後のスペースを入れない」という状態で最後まで書き切って、終盤で一括処理に近い感じで調整していく、というのがいいのではという気がします。

具体的に例をあげますと、たとえば、

> 私はPerlが好きです。

という文章であればスペースを入れるかどうかの判断は簡単ですが、

> 私は1日1回Perlを書きます。

という文章の場合、機械的に英数字の前後にスペースを入れると、` 1 日 1 回`のすべての文字間にスペースが入るので、やや違和感があります。

じゃあ「1日」のような場合だけ数字と漢字をくっつけても良いようにしよう、とローカルルールを作ると、今度は「1割」や「1メートル」はどうするのか？　という問題がどんどん派生的に生まれてきます。

つまり、この問題について考え始めると、そういう微妙な判断を必要とする場面がヤマのように出てきて、そのたびに毎回検討したり、一度決めたルールを忘れたり、あるいは一度決めたルールが気に入らなくなって全部修正し直したりすることになって結構大変ですし、またそういうことをくり返すうちに必ず抜け漏れが生じるので、そういう処理は逐次的にやるより、後でまとめる方が効率がいいのかなと。

むしろ、最初はそういったルール抜きで、マスターになる文章の執筆のみに集中して終わらせるだけでも充分労力を使うので、まずそちらから片付けるのがいいのでは、という意見です。

**Comment by ichigotake** [comment]
言われてみると全面的に納得ですね。仮に必要だったとしても現時点では「過度な最適化」となってしまいそうです。

このルールについては気にせず執筆していき、特別強調したいところだけは例外対応する、という形が良さそうですね。

いずれにしても、今は気にしないということでクローズします。
